venue:
  name: "Cobra's ZooKeeping Sport Center"
  timezone: "system"
  booking_window_days: 30
  hold_timeout_minutes: 5
  time_format_24h: true

accounts:
  users:
    - username: "user1"
      password: "pass1"
      balance_usd: 100
    - username: "user2"
      password: "pass2"
      balance_usd: 100
  admins:
    - username: "admin"
      password: "adminpass"

rates_usd_per_hour:
  badminton: 10
  pickleball: 40
  handball: 20
  skating: 60

courts:
  badminton: [B01, B02, B03, B04]
  pickleball: [PB01, PB02, PB03, PB04]
  handball: [H01, H02, H03, H04]
  skating: [SK01, SK02, SK03, SK04]
